version: '2'
services:
  jupyter:
    build: .
    ports:
      - 8888:8888
    volumes:
      - ./notebooks:/notebooks
      - ./.local:/home/jovyan/.local
      - ./.jupyter/nbconfig:/home/jovyan/.jupyter/nbconfig
      - ./.jupyter/custom:/home/jovyan/.jupyter/custom
